let employees = [
  {
    id: 1,
    first_name: "Verna",
    last_name: "Bettanay",
    email: "vbettanay0@taobao.com",
    gender: "Male",
    city: "Krandil",
  },
  {
    id: 2,
    first_name: "Hammad",
    last_name: "Pentercost",
    email: "hpentercost1@skype.com",
    gender: "Non-binary",
    city: "Tānsen",
  },
  {
    id: 3,
    first_name: "Kassi",
    last_name: "Stillwell",
    email: "kstillwell2@msn.com",
    gender: "Male",
    city: "Matou",
  },
  {
    id: 4,
    first_name: "Randolph",
    last_name: "Lamberts",
    email: "rlamberts3@cbsnews.com",
    gender: "Genderfluid",
    city: "Omoa",
  },
  {
    id: 5,
    first_name: "Maressa",
    last_name: "Daish",
    email: "mdaish4@arizona.edu",
    gender: "Polygender",
    city: "Niort",
  },
  {
    id: 6,
    first_name: "Fayina",
    last_name: "Teissier",
    email: "fteissier5@t-online.de",
    gender: "Non-binary",
    city: "Tsimlyansk",
  },
  {
    id: 7,
    first_name: "Natale",
    last_name: "Cattemull",
    email: "ncattemull6@ebay.co.uk",
    gender: "Female",
    city: "Yelan’",
  },
  {
    id: 8,
    first_name: "Luelle",
    last_name: "Adhams",
    email: "ladhams7@independent.co.uk",
    gender: "Non-binary",
    city: "Changqi",
  },
  {
    id: 9,
    first_name: "Cedric",
    last_name: "Treleven",
    email: "ctreleven8@devhub.com",
    gender: "Genderfluid",
    city: "Sumber",
  },
  {
    id: 10,
    first_name: "Corilla",
    last_name: "Isaacs",
    email: "cisaacs9@dell.com",
    gender: "Female",
    city: "Sosnovka",
  },
  {
    id: 11,
    first_name: "Aluino",
    last_name: "Swafield",
    email: "aswafielda@google.fr",
    gender: "Genderfluid",
    city: "Chicago",
  },
  {
    id: 12,
    first_name: "Crichton",
    last_name: "Mockett",
    email: "cmockettb@pen.io",
    gender: "Bigender",
    city: "Gamut",
  },
  {
    id: 13,
    first_name: "Thorstein",
    last_name: "Daysh",
    email: "tdayshc@biglobe.ne.jp",
    gender: "Genderqueer",
    city: "Tourcoing",
  },
  {
    id: 14,
    first_name: "Ibrahim",
    last_name: "Benedidick",
    email: "ibenedidickd@wp.com",
    gender: "Genderqueer",
    city: "Dob",
  },
  {
    id: 15,
    first_name: "Jerald",
    last_name: "Eads",
    email: "jeadse@foxnews.com",
    gender: "Agender",
    city: "Huaiyuan Chengguanzhen",
  },
  {
    id: 16,
    first_name: "Collin",
    last_name: "Race",
    email: "cracef@pcworld.com",
    gender: "Bigender",
    city: "Rasskazovo",
  },
  {
    id: 17,
    first_name: "Angelo",
    last_name: "Mullaly",
    email: "amullalyg@arizona.edu",
    gender: "Male",
    city: "Lijiang",
  },
  {
    id: 18,
    first_name: "Webb",
    last_name: "McCurley",
    email: "wmccurleyh@washington.edu",
    gender: "Genderfluid",
    city: "Mucllo",
  },
  {
    id: 19,
    first_name: "Beverley",
    last_name: "McKerton",
    email: "bmckertoni@patch.com",
    gender: "Agender",
    city: "Paraíba do Sul",
  },
  {
    id: 20,
    first_name: "Pauline",
    last_name: "Norvel",
    email: "pnorvelj@comsenz.com",
    gender: "Bigender",
    city: "Naagas",
  },
  {
    id: 21,
    first_name: "Livvie",
    last_name: "Wolledge",
    email: "lwolledgek@amazon.co.jp",
    gender: "Genderfluid",
    city: "Barreiro",
  },
  {
    id: 22,
    first_name: "Janeva",
    last_name: "Rhodef",
    email: "jrhodefl@google.co.jp",
    gender: "Genderfluid",
    city: "Singosari",
  },
  {
    id: 23,
    first_name: "Corena",
    last_name: "Ramsbotham",
    email: "cramsbothamm@moonfruit.com",
    gender: "Female",
    city: "Bershet’",
  },
  {
    id: 24,
    first_name: "Stanford",
    last_name: "Yarnell",
    email: "syarnelln@discovery.com",
    gender: "Non-binary",
    city: "Trnovska Vas",
  },
  {
    id: 25,
    first_name: "Maddie",
    last_name: "Winear",
    email: "mwinearo@nbcnews.com",
    gender: "Genderqueer",
    city: "Pyzdry",
  },
  {
    id: 26,
    first_name: "Leonhard",
    last_name: "Wallworke",
    email: "lwallworkep@digg.com",
    gender: "Non-binary",
    city: "Limushan",
  },
  {
    id: 27,
    first_name: "Rachael",
    last_name: "Brehat",
    email: "rbrehatq@infoseek.co.jp",
    gender: "Polygender",
    city: "Kuzhu",
  },
  {
    id: 28,
    first_name: "Iris",
    last_name: "Stayt",
    email: "istaytr@yolasite.com",
    gender: "Genderqueer",
    city: "Sihai",
  },
  {
    id: 29,
    first_name: "Demetris",
    last_name: "Tinner",
    email: "dtinners@amazonaws.com",
    gender: "Non-binary",
    city: "Las Flores",
  },
  {
    id: 30,
    first_name: "Walsh",
    last_name: "Secretan",
    email: "wsecretant@bloomberg.com",
    gender: "Agender",
    city: "Limeil-Brévannes",
  },
  {
    id: 31,
    first_name: "Gabriela",
    last_name: "Tennet",
    email: "gtennetu@thetimes.co.uk",
    gender: "Non-binary",
    city: "Cotorra",
  },
  {
    id: 32,
    first_name: "Sampson",
    last_name: "Douty",
    email: "sdoutyv@zimbio.com",
    gender: "Agender",
    city: "Cambridge",
  },
  {
    id: 33,
    first_name: "Perri",
    last_name: "Cape",
    email: "pcapew@edublogs.org",
    gender: "Male",
    city: "Mutengene",
  },
  {
    id: 34,
    first_name: "Davida",
    last_name: "Risborough",
    email: "drisboroughx@google.com.hk",
    gender: "Agender",
    city: "Nyima",
  },
  {
    id: 35,
    first_name: "Toby",
    last_name: "Bohje",
    email: "tbohjey@reference.com",
    gender: "Female",
    city: "Gostovići",
  },
  {
    id: 36,
    first_name: "Clevey",
    last_name: "Whitebrook",
    email: "cwhitebrookz@usgs.gov",
    gender: "Agender",
    city: "Taltal",
  },
  {
    id: 37,
    first_name: "Rochell",
    last_name: "Cluely",
    email: "rcluely10@blogspot.com",
    gender: "Genderqueer",
    city: "Celje",
  },
  {
    id: 38,
    first_name: "Stefan",
    last_name: "Kenzie",
    email: "skenzie11@yellowpages.com",
    gender: "Genderfluid",
    city: "Aubenas",
  },
  {
    id: 39,
    first_name: "Rainer",
    last_name: "Itzcovichch",
    email: "ritzcovichch12@ustream.tv",
    gender: "Agender",
    city: "Montauban",
  },
  {
    id: 40,
    first_name: "Winnifred",
    last_name: "Blades",
    email: "wblades13@istockphoto.com",
    gender: "Genderfluid",
    city: "Tuanjie",
  },
  {
    id: 41,
    first_name: "Jeramey",
    last_name: "Critchell",
    email: "jcritchell14@walmart.com",
    gender: "Bigender",
    city: "Xuchang",
  },
  {
    id: 42,
    first_name: "Tully",
    last_name: "Oubridge",
    email: "toubridge15@reuters.com",
    gender: "Polygender",
    city: "Cocachacra",
  },
  {
    id: 43,
    first_name: "Rodge",
    last_name: "Stranaghan",
    email: "rstranaghan16@columbia.edu",
    gender: "Female",
    city: "Ortiga",
  },
  {
    id: 44,
    first_name: "Iolande",
    last_name: "McLeary",
    email: "imcleary17@buzzfeed.com",
    gender: "Polygender",
    city: "Isojoki",
  },
  {
    id: 45,
    first_name: "Gifford",
    last_name: "Geistbeck",
    email: "ggeistbeck18@unblog.fr",
    gender: "Polygender",
    city: "Birmingham",
  },
  {
    id: 46,
    first_name: "Hermina",
    last_name: "Doles",
    email: "hdoles19@mysql.com",
    gender: "Male",
    city: "Tunggar",
  },
  {
    id: 47,
    first_name: "Upton",
    last_name: "Bowle",
    email: "ubowle1a@ca.gov",
    gender: "Genderfluid",
    city: "Cucutilla",
  },
  {
    id: 48,
    first_name: "Gilberte",
    last_name: "Blaise",
    email: "gblaise1b@ucoz.ru",
    gender: "Female",
    city: "Lékoni",
  },
  {
    id: 49,
    first_name: "Friedrich",
    last_name: "Yearby",
    email: "fyearby1c@foxnews.com",
    gender: "Bigender",
    city: "Carleton-sur-Mer",
  },
  {
    id: 50,
    first_name: "Tracy",
    last_name: "Fransewich",
    email: "tfransewich1d@nasa.gov",
    gender: "Genderqueer",
    city: "Kebunan",
  },
];

function dispaly() {
  let rows = "";
  for (let i = 0; i <= employees.length - 1; i++) {
    rows =
      rows +
      `<tr> <td> ${employees[i].id}</td>
            <td> ${employees[i].first_name}</td>
            <td> ${employees[i].city}</td>
            <td> ${employees[i].email}</td>
     </tr>`;
  }
  document.getElementById("table_body").innerHTML = rows;
}
